trigger:
- master
- develop

pr:
- master
- develop
- feature/*

name: $(Date:yyyyMMdd)$(Rev:rr)

pool:
  vmImage: 'ubuntu-latest'

variables:
  support_netstandard20: true
  support_netstandard21: true
  support_netcoreapp21: false
  support_netcoreapp31: true
  support_net5_0: true
  Major: 1
  Minor: 0
  Patch: 0

resources:
  repositories:
    - repository: templates
      type: github
      name: Sannel/Sannel.House.BuildScripts
      endpoint: Sannel

jobs:
- template: tasks/library.yml@templates  # Template reference